### ISSUE TITLE
Remove old AR Add Form Code

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#792]
## Todo

- [x] Remove https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analysisrequest/add.py
- [x] Remove https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analysisrequest/templates/ar_add_by_col.pt
- [x] Remove https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analysisrequest/templates/ar_add_by_row.pt
- [x] Remove https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
- [x] Cleanup https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analysisrequest/configure.zcml
